# Generated by Django 4.2.2 on 2024-02-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0003_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
    ]
