# Generated by Django 4.2.2 on 2024-01-19 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CartOrderProducts",
            new_name="CartOrderItems",
        ),
        migrations.RenameModel(
            old_name="wishlist_model",
            new_name="wishlist",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="in_stock",
            new_name="In_stock",
        ),
        migrations.RemoveField(
            model_name="address",
            name="mobile",
        ),
        migrations.RemoveField(
            model_name="cartorder",
            name="sku",
        ),
        migrations.RemoveField(
            model_name="product",
            name="life",
        ),
        migrations.RemoveField(
            model_name="product",
            name="mfd",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock_count",
        ),
        migrations.RemoveField(
            model_name="product",
            name="type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="vendor",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="date",
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.tags"
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="paid_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default="Here your product", null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="specifications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(default="Fresh meal", max_length=100),
        ),
        migrations.AlterField(
            model_name="productimages",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.product",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.product",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="address",
            field=models.CharField(default="TS1 Teesside University", max_length=100),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="contact",
            field=models.CharField(default="+44 7380592771", max_length=100),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="description",
            field=models.TextField(
                blank=True, default="Fast. Fresh. Flavorful.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="title",
            field=models.CharField(default="QuickCraze Eats", max_length=100),
        ),
    ]
