# Generated by Django 4.2.2 on 2024-01-19 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_cartorderproducts_cartorderitems_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="vendor_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="old_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
    ]
