# Generated by Django 4.2.2 on 2024-01-21 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_productimages_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="life",
            field=models.CharField(
                blank=True, default="100 Days", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="mfd",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_count",
            field=models.CharField(blank=True, default="10", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(
                blank=True, default="Organic", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="productimages",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_images",
                to="core.product",
            ),
        ),
    ]
