# Generated by Django 4.2.2 on 2024-01-21 20:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default="Here your product", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="specifications",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default="Fast. Fresh. Flavorful.", null=True
            ),
        ),
    ]
