# Generated by Django 4.2.2 on 2024-01-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_productreview_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="mobile",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
