# Generated by Django 4.2.2 on 2024-01-25 19:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0014_address_mobile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="wishlist",
            new_name="wishlist_model",
        ),
    ]
